# Generated by Django 2.2.12 on 2020-05-06 03:14

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonSocial', models.CharField(max_length=100)),
                ('ruc', models.CharField(help_text='RUC PERÚ', max_length=11, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(11)])),
                ('direccionFiscal', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
                ('telefono', models.CharField(help_text='051123456789', max_length=12, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(12)])),
                ('correo', models.EmailField(help_text='correo@dominio.com', max_length=254, unique=True)),
                ('cuenta', models.CharField(max_length=42)),
            ],
        ),
    ]
